### PR TITLE
fix some features on windows

### PR DESCRIPTION
**Pull request by etveritas**
Compile with VS2017 on Windows, and check Unix-like version on WSL.

### CODE REVIEW

**Comment by etveritas** [comment]
fix console text setting on Windows;
upload unistd.h for Windows;
delete detect platform of stdint.h；
fix some features on Windows in file_util.h;
And Happy The Spring Festival!

**Comment by aksnzhy** [comment]
That's great! I'll review these updates as soon as possible!

**Comment by aksnzhy** [comment]
@etveritas I build this pr on Mac, and I got the following compiler error:

xlearn-win/src/solver/trainer.cc:54:10: error: no member named 'print_row' in namespace 'Color'; did you
      mean 'print_now'?
  Color::print_row(str_list, width_list);

**Comment by etveritas** [comment]
@aksnzhy Oh, there is a typo in file format_print.h.

**Comment by etveritas** [comment]
@aksnzhy Already fixed it.

**Comment by aksnzhy** [comment]
@etveritas Hi, I have merged this PR to the master branch! Could you please write an installation guide for the windows in doc/install.rst ? You can write it in Chinese and I can help you translate it into English ! Thank you!

**Comment by etveritas** [comment]
@aksnzhy It haven't been finished now...

**Pull request merged**
