### PR TITLE
xlearn for windows

### PR DESCRIPTION
**Pull request by etveritas**
xLearn for Windows

Build on VS2017(x64), and pass all existing tests on windows10. Then check xLearn for unix-like version on WSL.
There are some information about this pull request.

Finished:
* xLearn for Windows including CLI and Python-package

Unfinished:
* test unittests with pthread.
* compile x86 release version(because fm_score_test haven't been passed for x86 release version).

Supplement:

I did not find what changes with the latest update for common.h, so I modify the program base on the last one before the latest update. There is only format change in some files.

### CODE REVIEW

**Comment by etveritas** [comment]
Only disable compile optimization on score.

**Comment by etveritas** [comment]
It's my finally change for this pull request if there is no bug you find.

**Comment by etveritas** [comment]
That's all my commits for this pull request.

**Comment by etveritas** [comment]
Hello, I build it on AppVeyor-CI, and there is my build log: https://ci.appveyor.com/project/etveritas/xlearn/builds/22613956

**Comment by etveritas** [comment]
@aksnzhy Is there any possible to review this pull request?

**Comment by aksnzhy** [comment]
> @aksnzhy Is there any possible to review this pull request?

Hi, I will review this code as soon as possible. By the way, could you write a page of installation guide for windows?

Thanks!

**Comment by etveritas** [comment]
@aksnzhy Of cause. hmm, and is there a template?

**Comment by aksnzhy** [comment]
> @aksnzhy Of cause. hmm, and is there a template?

You can reference this page: https://github.com/aksnzhy/xlearn/blob/master/doc/install.rst

and add a file  `install_windows.rst`

**Comment by aksnzhy** [comment]
> @aksnzhy Of cause. hmm, and is there a template?

Also, some of your code has the format error, e.g., using `tab` instead of `space`, or using 4 spaces instead of 2 spaces. Could you please modify this?

**Comment by etveritas** [comment]
> > @aksnzhy Of cause. hmm, and is there a template?
> 
> Also, some of your code has the format error, e.g., using `tab` instead of `space`, or using 4 spaces instead of 2 spaces. Could you please modify this?

Uh, I keep myself writing habit...I will modify it today. And where can I find the code and other rules?

**Comment by etveritas** [comment]
Because this pull request is mess for code review, I close this one and create new one soon later.

**Pull request closed without merging**
